include(FindPackageHandleStandardArgs)

find_library(XD_ENGINE_LIBRARY XDEngine HINTS "${CMAKE_BINARY_DIR}/Engine")
find_path(XD_ENGINE_MAIN_HEADER_DIR NAMES "XDEngine.h" PATHS "${XD_ROOT_SOURCE_PATH}/Engine/")

if(NOT ${XD_ENGINE_LIBRARY} STREQUAL "XD_ENGINE_LIBRARY-NOTFOUND")
    message("===| FOUND XD ENGINE LIB |===")
endif()

set(XD_ENGINE_INCLUDE_DIR)

if(XD_ENGINE_MAIN_HEADER_DIR)
    list(APPEND XD_ENGINE_INCLUDE_DIR "${XD_ENGINE_MAIN_HEADER_DIR}/Source")
endif()
